### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by kevinfields777** [dheid/micropolis#15]
Windows 10. Download micropolisj package. README says double-click on micropolis.bat.  Does nothing. 

Oh, maybe I need to install java. Follow link to Java.com, click big "Download Java" button, which takes me to "Version 8 Update 381 (filesize: 62.63 MB) Release date: July 18, 2023". Download, install.  Double-click on micropolis.bat.  Does nothing. 

Decide to open command line, run micropolis bat. Error message: 

Exception in thread "main" java.lang.UnsupportedClassVersionError: micropolisj/Micropolis has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
PS D:\games\micropolis-2.0.0\bin>

So Java8 was just updated a few months ago, but this file from 2020 was created with a newer clas?? 

Where do I find this Java Runtime class version 57? I can't find a download anywhere. How do I install it on Windows 10? ELI5 because I've been using computers for 35 years and I'm completely lost.  This is too much work! LOL

**Comment by kevinfields777** [comment]
Nevermind. Finally found Java 21 for download (WHY do they make it so hard for ordinary end-users??) and everything runs great now. 

An updated link would probably be helpful to many. https://www.oracle.com/java/technologies/downloads/#jdk21-windows
